"""Add dispute and club approval settings

Revision ID: 14ba96a62466
Revises: 8f72a1b3c4d5
Create Date: 2026-02-07 02:58:24.455095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '14ba96a62466'
down_revision: Union[str, Sequence[str], None] = '8f72a1b3c4d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clubs', sa.Column('approval_mode', sa.String(length=20), nullable=False))
    op.add_column('clubs', sa.Column('min_trust_score', sa.Numeric(precision=3, scale=1), nullable=True))
    op.drop_index(op.f('ix_clubs_region'), table_name='clubs')
    op.drop_column('clubs', 'recipient_name')
    op.drop_column('clubs', 'region')
    op.alter_column('complaints', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('complaints', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('deals', sa.Column('dispute_reason', sa.String(length=255), nullable=True))
    op.add_column('deals', sa.Column('paid_at', sa.DateTime(), nullable=True))
    op.alter_column('join_requests', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('join_requests', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('uq_join_requests_club_user'), 'join_requests', type_='unique')
    op.alter_column('pricing_services', 'region_restriction',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('pricing_services', 'popularity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('pricing_services', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('pricing_services', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('pricing_services', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_pricing_services_category'), table_name='pricing_services')
    op.drop_index(op.f('ix_pricing_services_is_active'), table_name='pricing_services')
    op.alter_column('telecom_operators', 'gb_min_volume',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('telecom_operators', 'popularity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('telecom_operators', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('telecom_operators', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('trust_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('users', 'weekly_deals_count')
    op.drop_column('users', 'recipient_name')
    op.drop_column('users', 'badges')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'avg_response_time_seconds')
    op.drop_column('users', 'phone_bank')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_bank', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('avg_response_time_seconds', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('badges', postgresql.ARRAY(sa.VARCHAR(length=30)), server_default=sa.text("'{}'::character varying[]"), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('recipient_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('weekly_deals_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('trust_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('telecom_operators', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('telecom_operators', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('telecom_operators', 'popularity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('telecom_operators', 'gb_min_volume',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_pricing_services_is_active'), 'pricing_services', ['is_active'], unique=False)
    op.create_index(op.f('ix_pricing_services_category'), 'pricing_services', ['category'], unique=False)
    op.alter_column('pricing_services', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('pricing_services', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('pricing_services', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('pricing_services', 'popularity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('pricing_services', 'region_restriction',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.create_unique_constraint(op.f('uq_join_requests_club_user'), 'join_requests', ['club_id', 'user_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('join_requests', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('join_requests', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_column('deals', 'paid_at')
    op.drop_column('deals', 'dispute_reason')
    op.alter_column('complaints', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('complaints', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.add_column('clubs', sa.Column('region', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('clubs', sa.Column('recipient_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_clubs_region'), 'clubs', ['region'], unique=False)
    op.drop_column('clubs', 'min_trust_score')
    op.drop_column('clubs', 'approval_mode')
    # ### end Alembic commands ###
