"""Initial schema

Revision ID: 29b8fdcd9e75
Revises: 7e69231183c1
Create Date: 2026-02-02 03:08:56.011847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29b8fdcd9e75'
down_revision: Union[str, Sequence[str], None] = '7e69231183c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions',
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('service_name', sa.String(length=100), nullable=False),
    sa.Column('service_name_kk', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('icon_url', sa.String(length=500), nullable=True),
    sa.Column('max_members', sa.Integer(), nullable=False),
    sa.Column('official_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('subscription_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('trust_score', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('scam_reports', sa.Integer(), nullable=False),
    sa.Column('p2p_deals_count', sa.Integer(), nullable=False),
    sa.Column('p2p_success_count', sa.Integer(), nullable=False),
    sa.Column('p2p_total_volume_gb', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_active_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('account_offers',
    sa.Column('offer_id', sa.UUID(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('service_category', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['seller_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('offer_id')
    )
    op.create_table('clubs',
    sa.Column('club_id', sa.UUID(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('price_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('price_per_member', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('max_members', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('payment_details', sa.String(length=255), nullable=True),
    sa.Column('payment_day', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rules', sa.Text(), nullable=True),
    sa.Column('telegram_group_link', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['host_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.subscription_id'], ),
    sa.PrimaryKeyConstraint('club_id')
    )
    op.create_index('ix_clubs_category', 'clubs', ['category'], unique=False)
    op.create_index('ix_clubs_host_id', 'clubs', ['host_id'], unique=False)
    op.create_index('ix_clubs_status', 'clubs', ['status'], unique=False)
    op.create_table('gigabyte_offers',
    sa.Column('offer_id', sa.UUID(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('operator', sa.String(length=50), nullable=False),
    sa.Column('amount_gb', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['seller_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('offer_id')
    )
    op.create_table('club_members',
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('club_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('last_payment_at', sa.DateTime(), nullable=True),
    sa.Column('next_payment_due', sa.DateTime(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.Column('left_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.club_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('member_id')
    )
    op.create_index('ix_club_members_status', 'club_members', ['status'], unique=False)
    op.create_table('deals',
    sa.Column('deal_id', sa.UUID(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('offer_type', sa.String(length=20), nullable=False),
    sa.Column('gb_offer_id', sa.UUID(), nullable=True),
    sa.Column('club_id', sa.UUID(), nullable=True),
    sa.Column('account_offer_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('proof_screenshot_id', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_offer_id'], ['account_offers.offer_id'], ),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.club_id'], ),
    sa.ForeignKeyConstraint(['gb_offer_id'], ['gigabyte_offers.offer_id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('deal_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deals')
    op.drop_index('ix_club_members_status', table_name='club_members')
    op.drop_table('club_members')
    op.drop_table('gigabyte_offers')
    op.drop_index('ix_clubs_status', table_name='clubs')
    op.drop_index('ix_clubs_host_id', table_name='clubs')
    op.drop_index('ix_clubs_category', table_name='clubs')
    op.drop_table('clubs')
    op.drop_table('account_offers')
    op.drop_table('users')
    op.drop_table('subscriptions')
    # ### end Alembic commands ###
